<h1 id="curing-languor-and-laziness-in-seeking-knowledge">Curing Languor and Laziness in Seeking Knowledge</h1>
<ol type="1">
<li>Supplication, hope, humility and brokenness before God – this is by supplicating by the supplication of the Prophet صلى الله عليه وسلم: “Oh Allah, I seek refuge in you from worry, grief, incapacity, and laziness.”</li>
<li>Reviewing one’s intention in seeking knowledge and making them purely for God جل جلاله and taking the means of success in righteous works like prayer, charity, and seeking parents’ supplications – nothing succeeds without this.</li>
<li>Feeling the gravity and immense responsibility borne on his shoulders, and constantly reminding oneself of this fact, for one is obligated to change himself from ignorance to knowledge, from sitting to walking, and from blindness to sight; he is obligated to do that with his family and close companions as well – his spouse and children, then whoever surrounds him and interacts with him.</li>
<li>To shift from science to science, like shifting from jurisprudence to exegesis to hadith, etc, or from one way of studying to another, like shifting from reciting to listening, or to researching or memorizing, etc.</li>
<li>Reading from the books of those with lofty aspirations, like reading the biographies and stories of the early leaders or books like Shaykh ‘Abd al-Fattāḥ Abū Ghudda’s Qīmat al-Zaman ‘ind al-‘Ulamā’ or Ṣafaḥāt min Ṣabr al-‘Ulamā’.</li>
<li>Perusing books about the virtues of seeking knowledge, its methods, its etiquettes, and the love and states of the scholars regarding it</li>
<li>Visiting serious students of knowledge and keeping their company while they work in reading or researching or reviewing any topic, for resembling beings attract each other, and a companion drags one along, so he will take you by your hand in your hour of languor</li>
<li>Balance in eating, drinking, and sleeping: whoever eats a lot will drink a lot, and whoever drinks a lot will sleep a lot, and whoever sleeps a lot misses out on a lot of good</li>
<li>Investigating the causes of languor and its cures and a method to keep it away. Among these causes are over-engagement with this world, increasing in its various pleasures, and immersion in sin</li>
<li>Knowing that he is struggling to raise the word of God by proof and exposition, which is no less than the weight of martial jihad by the sword and spear, if not greater</li>
<li>Gentleness with the soul lest one burden himself with more than his capacity and fall, and charge oneself with that which he cannot do lest he leave it and languish. One should be diplomatic and use tricks regarding those things that weigh heavily on him so he becomes accustomed to completing it</li>
<li>Intention and moderation when considering exemplary models of memorization, understanding, acquiring knowledge, writing books, calling to Islam, and other works. One should not seek to become a marvelous memorizer like so-and-so, or attain deep comprehension like so-and-so, or become is writing or inviting to Islam like so-and-so and such-and such, especially when he has not studied except for a few paltry years while those exemplary models have spent their lifetimes in knowledge. Moreover, they are of different circumstances than he is. Therefore a student should not seek to hasten to that which he is not yet suited for and thus flee from that which is suited for him.</li>
</ol>
